#!/bin/bash
#demande quelle action faire
echo "----------------------------"
echo "|  liste des informations   |"
echo "----------------------------"
echo "| [1]Nombre de disque       |"
echo "| [2]Details partition      |"
echo "| [3]Espace restant         |"
echo "| [4]Détail dossier         |"
echo "| [5]Liste lecteurs         |"
echo "| [*]sortie                 |"
echo "|---------------------------"
read -p " A quel service souhaitez-vous avoir accès? [1 2 3 4 5 *] : " actionHost

case $actionHost in
    # dans le cas 1
    # Fonction -> Nombre de disque
  1) lshw -class disk
        ;;
    # dans le cas 2
    # Fonction -> Partition (nombre, nom, FS, taille) par disque
  2) df -h
        ;;
    # dans le cas 3
    # Fonction -> Espace disque restant par partition/volume
  3) df -h | awk '{print $1 "-----" $4}'
        ;;
    # dans le cas 4
    # Fonction -> Nom et espace disque d'un dossier (nom de dossier demandé)
  4) read -p "Quel dossier?" choix_dossier
        if [ -d "$choix_dossier" ]
        then
          find . -type d -name $choix_dossier | du -hs

        else
            echo "Le nom de dossier n'existe pas"
        exit 1
        fi 
        ;;

    # dans le cas 5 
    # Fonction -> Liste des lecteurs monté (disque, CD, etc.)
  5) lsblk 
        ;;
        #sortie retour menu
  *) exit 1 
        ;;
esac
exit 0
